# Generated by Django 4.0.3 on 2022-04-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_purchase', models.DateField(auto_now=True)),
            ],
        ),
    ]
